name: school_soft_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  
  flutter_riverpod: ^2.0.1
  go_router: ^4.4.1
  
  uuid: ^3.0.6

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  firebase_core: ^1.23.0
  firebase_auth: ^3.10.0

  google_sign_in: ^5.4.2

  shared_preferences: ^2.0.15

  dio: ^4.0.6

dev_dependencies:
  hive_generator: ^2.0.0
  build_runner: ^2.3.2

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
